export const FETCH_SUGGESTIONS_START = 'FETCH_SUGGESTIONS_START';
export const RECIEVE_SUGGESTIONS = 'RECIEVE_SUGGESTIONS';
export const FETCH_SUGGESTIONS_FAIL = 'FETCH_SUGGESTIONS_FAIL';
export const CLEAR_SUGGESTIONS = 'CLEAR_SUGGESTIONS';

export const FETCH_LOCATION_WEATHER_START = 'FETCH_LOCATION_WEATHER_START';
export const RECIEVE_LOCATION_WEATHER = 'FETCH_LOCATION_WEATHER';
export const FETCH_LOCATION_WEATHER_FAIL = 'FETCH_LOCATION_WEATHER';